@startuml

folder global.namespace.archive-io {
    [archive-io-api] <|-- [archive-io-commons-compress]
    [archive-io-api] <-- [archive-io-delta]
    [archive-io-api] <|-- [archive-io-bios]
    [archive-io-bios] -[hidden] [archive-io-commons-compress]
}

[commons-compress] <--- [archive-io-commons-compress]
[fun-io-jackson] <--- [archive-io-delta]
[fun-io-api] <-- [archive-io-api]
[fun-io-api] <-- [fun-io-bios]
[fun-io-api] <-- [fun-io-jackson]
[fun-io-bios] <--- [archive-io-commons-compress]
[fun-io-bios] <--- [archive-io-delta]
[fun-io-bios] <--- [archive-io-bios]

[archive-io-delta] "this" <-- [client-application]
[archive-io-bios] "and either this" <.. [client-application]
[archive-io-commons-compress] "or that" <.. [client-application]

@enduml
